# Use this file to configure Fiji's primary Python environment.

name: fiji
channels:
  - conda-forge
dependencies:
  - python = 3.12
  - pip
  - pip:
    - pyimagej>=1.7.0 # required! see config/jaunch/fiji.py
    - git+https://github.com/apposed/appose-python.git@efe6dadb2242ca45820fcbb7aeea2096f99f9cb2
    # Niceties:
    - scikit-image
    - napari[all]
    - napari-imagej
    - ndv[qt]
